### ISSUE TITLE
1.12 support

### ISSUE THREAD

**Issue by zedwick** [Thinkofname/vanillacord#4]
Vanillacord doesn't appear to work with the latest 1.12 build

```
$ java -jar vanillacord.jar 1.12
Downloading
Loading
Found the login listener in pa.class
Exception in thread "main" java.lang.NullPointerException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at uk.co.thinkofdeath.vanillacord.Main.main(Main.java:105)
```

**Comment by clowrym** [comment]
Same issue:
`root@e597d406567d:/var/games/minecraft# java -jar vanillacord.jar 1.12
Downloading
Loading
Found the login listener in pa.class
Exception in thread "main" java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at uk.co.thinkofdeath.vanillacord.Main.main(Main.java:105)`

**Comment by Bayside308** [comment]
Unfortunately, I'm also having the same issue. @Thinkofname, do you plan on updating?

**Comment by Thinkofname** [comment]
I haven't played minecraft in over a year and haven't been keeping track of the changes, sorry.

**Comment by ME1312** [comment]
Might you merge #5 if it is working then?

**Comment by Thinkofname** [comment]
From a glance it looks like that PR breaks all other versions in the process. 

At this point I have no issues if someone wants to fork this and maintain it themselves as I don't have the time to keep it up to date with Minecraft anymore.
